npx @amplicode/codegen react-typescript:entity-management\
 --schema ../src/main/resources/graphql/schema.graphqls\
 --dest ../frontend/src/app/screens/owner\
 --dirShift ../../../\
 --answers eyJsaXN0Q29tcG9uZW50TmFtZSI6Ik93bmVyQ2FyZHMiLCJpdGVtQ29tcG9uZW50TmFtZSI6Ik93bmVyQ2FyZHNFZGl0b3IiLCJyb3V0ZSI6I\
m93bmVyLWNhcmRzIiwic2hvdWxkQWRkVG9NZW51Ijp0cnVlLCJsaXN0UXVlcnkiOiJxdWVyeSBHZXRfT3duZXJfTGlzdCB7XG4gICAgb3duZXJMaXN0IHtc\
biAgICAgIG93bmVySWRcbiAgICAgIGZpcnN0TmFtZVxuICAgICAgbGFzdE5hbWVcbiAgICB9XG4gIH0iLCJkZXRhaWxzUXVlcnkiOiJxdWVyeSBHZXRfT3d\
uZXIoJGlkOiBJRCkge1xuICAgIG93bmVyKG93bmVySWQ6ICRpZCkge1xuICAgICAgb3duZXJJZFxuICAgICAgZmlyc3ROYW1lXG4gICAgICBsYXN0TmFtZV\
xuICAgIH1cbiAgfSIsImRlbGV0ZU11dGF0aW9uIjoibXV0YXRpb24gRGVsZXRlX093bmVyKCRpZDogSUQhKSB7XG4gICAgZGVsZXRlT3duZXIob3duZXJJZ\
DogJGlkKVxuICB9IiwidXBzZXJ0TXV0YXRpb24iOiJtdXRhdGlvbiBVcGRhdGVfT3duZXIoJGlucHV0OiBPd25lcklucHV0RFRPSW5wdXQpIHtcbiAgICB1\
cGRhdGVPd25lcihpbnB1dDogJGlucHV0KSB7XG4gICAgICBvd25lcklkXG4gICAgfVxuICB9In0=
